# Generated by Django 5.2.7 on 2025-10-16 15:29

import django_ckeditor_5.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-идентификатор')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержимое поста', config_name='extends')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Изображение (превью)')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Пост в блоге',
                'verbose_name_plural': 'Посты в блоге',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('order', models.IntegerField(default=100, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Раздел услуг',
                'verbose_name_plural': 'Разделы услуг',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL-идентификатор услуги')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Подробное описание услуги', config_name='extends')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('order', models.IntegerField(default=100, verbose_name='Порядок отображения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.servicecategory', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'title'],
            },
        ),
    ]
