"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy

load_dotenv() 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fx42c0a1u&j=3rch=p$#5yk5#ud=t0d9ygimm7=a=r$c%i7_2c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',  # Django Unfold должен быть перед django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'blog',
    'services',
    'pages',
    'seo',
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.GeoLocationMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'main.context_processors.services_menu',
            ],
            'builtins': [
                'main.templatetags.global_filters',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', '').lower()
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')

# Если Postgres явно выбран и есть имя БД — используем Postgres, иначе SQLite
if DB_ENGINE in ('postgres', 'postgresql', 'psql') and DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST or 'localhost',
            'PORT': DB_PORT or '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Кэширование отключено для разработки
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
# Путь, куда `collectstatic` будет собирать все статические файлы для продакшена
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User-uploaded content)
# URL для доступа к медиафайлам в браузере
MEDIA_URL = '/media/'
# Путь в файловой системе, где будут храниться загруженные файлы
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor settings
# Обязательно для работы загрузчика изображений
CKEDITOR_UPLOAD_PATH = 'uploads/'
# Убирает надпись "CKEditor 4" внизу редактора
CKEDITOR_FORCE_JPEG_COMPRESSION = True
CKEDITOR_IMAGE_QUALITY = 75

# Конфигурация панели инструментов CKEditor
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'toolbar_Full': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'],
            ['Link', 'Unlink', 'Anchor'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language'],
            ['Source', '-', 'Maximize'],
        ],
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки для геолокации
# IPAPI_KEY = 'your_api_key_here'  # Получить на https://ipapi.co/api/
# Без ключа: 1000 запросов/день, только HTTP
# С ключом: больше запросов, HTTPS, больше данных

# Настройки Django Unfold
UNFOLD = {
    "SITE_TITLE": "Isakov Agency - путник, ты нашел свое место...",
    "SITE_HEADER": "Путник, ты нашел свое место...",
    "SITE_SYMBOL": "👹",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "Isakov Agency Development",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "🏙️ Региональное SEO",
                "separator": True,
                "items": [
                    {
                        "title": "Города",
                        "icon": "location_city",
                        "link": lambda request: reverse_lazy("admin:main_city_changelist"),
                    },
                ],
            },
            {
                "title": "💼 Услуги",
                "separator": True,
                "items": [
                    {
                        "title": "Категории услуг",
                        "icon": "folder",
                        "link": lambda request: reverse_lazy("admin:main_servicecategory_changelist"),
                    },
                    {
                        "title": "Услуги",
                        "icon": "business",
                        "link": lambda request: reverse_lazy("admin:main_service_changelist"),
                    },
                ],
            },
            {
                "title": "📝 Контент",
                "separator": True,
                "items": [
                    {
                        "title": "Блог",
                        "icon": "article",
                        "link": lambda request: reverse_lazy("admin:main_post_changelist"),
                    },
                    {
                        "title": "Команда",
                        "icon": "people",
                        "link": lambda request: reverse_lazy("admin:main_teammember_changelist"),
                    },
                    {
                        "title": "Отзывы",
                        "icon": "star",
                        "link": lambda request: reverse_lazy("admin:main_testimonial_changelist"),
                    },
                ],
            },
        ],
    },
}