"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy

load_dotenv() 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fx42c0a1u&j=3rch=p$#5yk5#ud=t0d9ygimm7=a=r$c%i7_2c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',  # Django Unfold должен быть перед django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'blog',
    'services',
    'pages',
    'team',
    'portfolio',
    'utils',
    'seo',
    'seo_management',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.RedirectMiddleware',  # Редиректы должны быть рано в цепочке
    'main.middleware.GeoLocationMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'main.context_processors.services_menu',
            ],
            'builtins': [
                'main.templatetags.global_filters',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', '').lower()
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')

# Если Postgres явно выбран и есть имя БД — используем Postgres, иначе SQLite
if DB_ENGINE in ('postgres', 'postgresql', 'psql') and DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST or 'localhost',
            'PORT': DB_PORT or '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Кэширование отключено для разработки
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
# Путь, куда `collectstatic` будет собирать все статические файлы для продакшена
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Дополнительные директории со статическими файлами
STATICFILES_DIRS = [
    BASE_DIR / 'main' / 'static',
]

# Media files (User-uploaded content)
# URL для доступа к медиафайлам в браузере
MEDIA_URL = '/media/'
# Путь в файловой системе, где будут храниться загруженные файлы
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor 5 settings
customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
        'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки для геолокации
# IPAPI_KEY = 'your_api_key_here'  # Получить на https://ipapi.co/api/
# Без ключа: 1000 запросов/день, только HTTP
# С ключом: больше запросов, HTTPS, больше данных

# Настройки Django Unfold
UNFOLD = {
    "SITE_TITLE": "Isakov Agency - путник, ты нашел свое место...",
    "SITE_HEADER": "Путник, ты нашел свое место...",
    "SITE_SYMBOL": "👹",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "Isakov Agency Development",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "🏙️ Региональное SEO",
                "separator": True,
                "items": [
                    {
                        "title": "Города",
                        "icon": "location_city",
                        "link": lambda request: reverse_lazy("admin:main_city_changelist"),
                    },
                    {
                        "title": "Региональные адаптации статей",
                        "icon": "article",
                        "link": lambda request: reverse_lazy("admin:main_regionalpostadaptation_changelist"),
                    },
                ],
            },
            {
                "title": "💼 Услуги",
                "separator": True,
                "items": [
                    {
                        "title": "Категории услуг",
                        "icon": "folder",
                        "link": lambda request: reverse_lazy("admin:main_servicecategory_changelist"),
                    },
                    {
                        "title": "Услуги",
                        "icon": "business",
                        "link": lambda request: reverse_lazy("admin:main_service_changelist"),
                    },
                ],
            },
            {
                "title": "📝 Блог",
                "separator": True,
                "items": [
                    {
                        "title": "Категории блога",
                        "icon": "folder",
                        "link": lambda request: reverse_lazy("admin:blog_category_changelist"),
                    },
                    {
                        "title": "Статьи блога",
                        "icon": "article",
                        "link": lambda request: reverse_lazy("admin:blog_post_changelist"),
                    },
                ],
            },
            {
                "title": "👥 Команда и отзывы",
                "separator": True,
                "items": [
                    {
                        "title": "Участники команды",
                        "icon": "people",
                        "link": lambda request: reverse_lazy("admin:main_teammember_changelist"),
                    },
                    {
                        "title": "Отзывы клиентов",
                        "icon": "star",
                        "link": lambda request: reverse_lazy("admin:main_testimonial_changelist"),
                    },
                ],
            },
            {
                "title": "💼 Портфолио",
                "separator": True,
                "items": [
                    {
                        "title": "Работы в портфолио",
                        "icon": "work",
                        "link": lambda request: reverse_lazy("admin:main_portfolioitem_changelist"),
                    },
                ],
            },
            {
                "title": "📄 Заявки",
                "separator": True,
                "items": [
                    {
                        "title": "Заявки с сайта",
                        "icon": "mail",
                        "link": lambda request: reverse_lazy("admin:main_contactrequest_changelist"),
                    },
                ],
            },
            {
                "title": "🔍 SEO и система",
                "separator": True,
                "items": [
                    {
                        "title": "Кастомные скрипты",
                        "icon": "code",
                        "link": lambda request: reverse_lazy("admin:main_customheadscript_changelist"),
                    },
                    {
                        "title": "Хлебные крошки",
                        "icon": "menu",
                        "link": lambda request: reverse_lazy("admin:seo_breadcrumb_changelist"),
                    },
                    {
                        "title": "Sitemap",
                        "icon": "map",
                        "link": lambda request: reverse_lazy("admin:seo_management_sitemapsettings_changelist"),
                    },
                    {
                        "title": "Robots.txt",
                        "icon": "settings",
                        "link": lambda request: reverse_lazy("admin:seo_management_robotstxtsettings_changelist"),
                    },
                ],
            },
            {
                "title": "📄 Страницы",
                "separator": True,
                "items": [
                    {
                        "title": "Статические страницы",
                        "icon": "description",
                        "link": lambda request: reverse_lazy("admin:pages_simplepage_changelist"),
                    },
                ],
            },
            {
                "title": "👥 Пользователи и группы",
                "separator": True,
                "items": [
                    {
                        "title": "Пользователи",
                        "icon": "person",
                        "link": lambda request: reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Группы",
                        "icon": "group",
                        "link": lambda request: reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
    "DASHBOARD_CALLBACKS": [],
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇺🇸",
                "ru": "🇷🇺",
            },
        },
    },
    "SILENCED_SYSTEM_CHECKS": ["security.W019"],
    "HIDE_APPS": [
        "auth",
        "contenttypes", 
        "sessions",
        "admin",
        "pages",
        "seo"
    ],
}

# Настройки админки
ADMIN_COLLAPSED_GROUPS = [
    'main',
    'blog', 
    'services',
    'seo',
    'seo_management',
    'pages'
]